Citesphere app page
diging/diging pull request #54
Opened 2021-02-08 19:53 UTC by adhvikmadhav

2021-02-09 14:39 UTC, jdamerow commented
- in the dropdown menu "our work", none of the app links work
- let's keep the github commit activity, maybe put it below FAQs
- there are issues with the dark mode
- also the dark mode is not kept anymore, when I go to another page it's in the light mode again
- on the Citesphere page, let's put the "Sync your Zotero citations." sections first.

please reopen this PR next time, so the comments are kept.

2021-02-09 15:01 UTC, jdamerow commented
also, let's add the link to the citephere documentation (https://diging.atlassian.net/wiki/spaces/CITED/overview).

2021-02-10 20:04 UTC, adhvikmadhav commented
Review

2021-02-23 14:46 UTC, jdamerow requested changes
The links to the Citesphere page don't work.

2021-02-23 14:46 UTC, jdamerow commented on _includes/asu_navigation.html
> +        // {% endfor %}
remove if not needed

2021-02-23 14:46 UTC, jdamerow commented on projects/index2.html
> +										</div> -->
remove if no longer needed

2021-02-23 14:46 UTC, jdamerow commented on projects/index2.html
> +										</div> -->
same as above (remove if not needed)

2021-03-04 15:58 UTC, jdamerow requested changes

2021-03-04 15:58 UTC, jdamerow commented on _data/applications.yml
> +  description: "Manage your citations and more."
Let's make this "Manage your references and more."

2021-03-04 15:58 UTC, jdamerow commented on _data/applications.yml
> +  description: "Build virtual exhibitions through 2D space."
"Build virtual exhibitions online."

2021-03-04 15:58 UTC, jdamerow commented on _data/projects.yml
> +  desc: "Network map of remarkable women engineers."
Network map of remarkable women in computer science.

2021-03-04 15:58 UTC, jdamerow commented on _data/tools.yml
> +  desc: "Import JSTOR data for corpus analysis into Elasticsearch."
Import your JSTOR data into Elasticsearch.

2021-03-04 15:58 UTC, jdamerow commented
The link to citesphere on the "Our work" page doesn't work.

2021-03-05 15:06 UTC, merged